/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.wm.java-conventions")
}

dependencies {
    api(project(":boogle-common"))
    api(project(":boogle-logging"))
}

description = "系统管理模块"
