/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.wm.java-conventions")
}

dependencies {
    implementation(project(":boogle-core"))
    implementation(project(":boogle-common"))
}

description = "日志模块"
