spring:
  application:
    name: demo-service
  profiles:
    active: prod
  cloud:
    nacos:
      config:
        #nacos 地址
        #server-addr: 192.168.1.5:8848
        server-addr: 192.168.1.5:8848
        # 命名空间
        namespace: prod
        # 分组
        group: DEFAULT_GROUP
        # 配置文件名前缀
        # prefix: ${spring.application.name}
        # 配置文件名后缀
        file-extension: yml
#        shared-configs:
#          - common-test.yml

  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - optional:nacos:common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}