version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ./base-server/nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./base-server/nacos/standalone-logs/:/home/nacos/logs
      - ./base-server/nacos/init.d/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql8
    build:
      context: .
      dockerfile: ./base-server/mysql8/Dockerfile
    image: example/mysql:8.0.30
    # command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./base-server/mysql8/mysql.env
    volumes:
      - ./base-server/mysql8/mysql:/var/lib/mysql
    ports:
      - target: 3306
        published: 3309
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  redis-alpine:
    container_name: redis-alpine
    image: "redis:alpine"
    ports:
      - target: 6379
        published: 6380
    networks:
      wm-net:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./base-server/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure


# 网络
networks:
  wm-net: