/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.wm.java-conventions")
}

dependencies {
    api(project(":boogle-core"))
    api("org.springframework.boot:spring-boot-starter-aop")
    api("org.springframework.boot:spring-boot-starter-data-redis")
    api("commons-fileupload:commons-fileupload:1.4")
    api("mysql:mysql-connector-java:8.0.28")
    api("org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.1")
    api("eu.bitwalker:UserAgentUtils:1.21")
    api("cn.hutool:hutool-all:5.8.0")
    api("com.github.penggle:kaptcha:2.3.2")
}

description = "通用工具模块"
