
# ????
gen:
  # ??
  author: wm
  # ??????? system ?????????? ? system monitor tool
  packageName: org.wm.system
  # ???????????false
  autoRemovePre: false
  # ????????????????????????
  tablePrefix: sys_