/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.wm.java-conventions")
}

dependencies {
    implementation(project(":boogle-common"))
    implementation(project(":boogle-logging"))
    implementation("org.quartz-scheduler:quartz:2.3.2")
}

description = "定时任务模块"
