spring:
  profiles:
    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
mybatis:
  typeAliasesPackage: org.wm.**.domain,org.wm.**.entity
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

task:
  pool:
    core-pool-size: 10
    max-pool-size: 15
    keep-alive-seconds: 5000
    queue-capacity: 5

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
springdoc:
  version: v1.0.0
  swagger-ui:
    # path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
    csrf:
      enabled: true
    enabled: true
  show-actuator: true
  group-configs:
    - group: systems
      paths-to-match: /system/**
      packages-to-scan: org.wm.controller
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: org.wm.controller
  paths-to-match: /system/**
app:
  captcha-type: char
